### ISSUE TITLE
ORM does not auto-discover database connection from DATABASE_URL

### ISSUE THREAD

**Issue by justin-k-bruce** [tina4stack/tina4-php#104]
## Bug

When `DATABASE_URL` (along with `DATABASE_USERNAME` and `DATABASE_PASSWORD`) is configured in `.env`, ORM models instantiated without an explicit database adapter throw:

```
ORM: No database adapter set. Call setDb() first.
```

The framework provides `App::getDatabase()` which correctly creates a connection from `DATABASE_URL` via `Database::fromEnv()`, but the ORM's constructor does not use it as a fallback.

## Expected Behaviour

```php
$customer = new Customer();
$customer->selectOne("select * from customer where username = ?", ["test"]); // Should work — DATABASE_URL is configured
```

The ORM should auto-discover the database connection from `App::getDatabase()` when no adapter is explicitly provided, similar to how most active record implementations work (e.g., Laravel Eloquent, Rails ActiveRecord).

## Actual Behaviour

```php
$customer = new Customer();
$customer->selectOne("select * from customer where username = ?", ["test"]); // Throws: "ORM: No database adapter set. Call setDb() first."
```

Every ORM usage requires explicitly passing the adapter:

```php
$db = App::getDatabase()->getAdapter();
$customer = new Customer($db);
```

## Root Cause

The ORM constructor (`ORM.php` line ~117) accepts `?DatabaseAdapter $db = null` and simply stores it:

```php
public function __construct(?DatabaseAdapter $db = null, array $data = [])
{
    $this->_db = $db;
    // ...
}
```

When `$db` is `null`, it stays `null`. The `ensureDb()` check (called by `save()`, `selectOne()`, `where()`, `delete()`, etc.) then throws because `_db` is never resolved.

Additionally, `App::getDatabase()` returns a `Database` wrapper object, not a `DatabaseAdapter`. So even if auto-discovery were added, it would need to call `->getAdapter()` to satisfy the type constraint.

## Impact

This is a significant usability issue. In a typical application with dozens of ORM models used across many files, every single instantiation site must manually fetch and pass the database adapter. For example, our project has **50 ORM models** and **160+ instantiation sites** — all of which fail without explicit adapter injection.

## Suggested Fix

In `ORM::__construct()`, fall back to `App::getDatabase()` when no adapter is provided:

```php
public function __construct(?DatabaseAdapter $db = null, array $data = [])
{
    if ($db === null) {
        $appDb = \Tina4\App::getDatabase();
        if ($appDb instanceof \Tina4\Database\Database) {
            $db = $appDb->getAdapter();
        } elseif ($appDb instanceof DatabaseAdapter) {
            $db = $appDb;
        }
    }
    $this->_db = $db;

    if (!empty($data)) {
        $this->fill($data);
    }
}
```

This preserves the ability to pass an explicit adapter, but makes the common case (`new Model()`) work out of the box when `DATABASE_URL` is configured.

## Current Workaround

We created a `BaseORM` class that all models extend instead of `\Tina4\ORM`:

```php
abstract class BaseORM extends \Tina4\ORM
{
    public function __construct(?DatabaseAdapter $input = null, array $data = [])
    {
        if ($input === null) {
            $dbInstance = \Tina4\App::getDatabase();
            $input = ($dbInstance instanceof Database) ? $dbInstance->getAdapter() : $dbInstance;
        }
        parent::__construct($input, $data);
    }
}
```

## Environment

- PHP 8.4.8
- Tina4 v3.10.49
- Firebird (but applies to all database adapters)

**Comment by andrevanzuydam** [comment]
Thanks for the feature request — this is a real gap in the current v3 ORM.

Right now, `ORM::ensureDb()` throws a `RuntimeException` if no adapter has been set via `setDb()`. There is no automatic discovery from `DATABASE_URL` or any other environment variable. The pattern today is explicit:

```php
$db = Database::fromEnv(); // reads DATABASE_URL + DATABASE_USERNAME + DATABASE_PASSWORD
$model = new User($db);
// or
$model->setDb($db);
```

Your request is valid — ORM models should be able to auto-connect from `DATABASE_URL` (and `DATABASE_USERNAME` / `DATABASE_PASSWORD`) when no adapter is injected, making simple use cases zero-boilerplate.

We'll add lazy auto-discovery in `ensureDb()`: if `_db` is null and `DATABASE_URL` is set in the environment, call `Database::fromEnv()` automatically. Explicit `setDb()` will always take precedence over auto-discovery.

**Comment by andrevanzuydam** [comment]
Fixed in v3.10.54 — `ensureDb()` now auto-discovers from `DATABASE_URL` (and optional `DATABASE_USERNAME`/`DATABASE_PASSWORD`) env vars when no explicit `orm_bind()` has been called. Works across all 4 frameworks.

**Comment by justin-k-bruce** [comment]
Thanks for the update, but this isn't fully working in v3.10.60. Two issues:

**1. `ensureDb()` assigns `Database` to a `DatabaseAdapter` typed property**

The fix in `ensureDb()` (line 1244-1248) calls `Database::fromEnv()` which returns a `Database` object, but `$_db` is typed as `?DatabaseAdapter`:

```php
// ORM.php line 54
protected ?DatabaseAdapter $_db = null;

// ensureDb() line 1245-1247
$discovered = \Tina4\Database\Database::fromEnv();
if ($discovered !== null) {
    $this->_db = $discovered; // Type mismatch: Database is not DatabaseAdapter
}
```

`Database` does not implement `DatabaseAdapter`, so this is a type mismatch. It should be:

```php
$discovered = \Tina4\Database\Database::fromEnv();
if ($discovered !== null) {
    $this->_db = $discovered->getAdapter();
}
```

**2. Constructor still doesn't auto-discover**

The constructor still just does `$this->_db = $db` (line 120). Auto-discovery only happens lazily in `ensureDb()`. While this works for data operations (since they call `ensureDb()`), it means `$model->getDb()` returns `null` until the first data method is called — which can be confusing and breaks code that checks `getDb()` before using the model.

Our `BaseORM` workaround remains necessary because it resolves the adapter eagerly in the constructor and correctly unwraps `Database` → `DatabaseAdapter`.

**Comment by andrevanzuydam** [comment]
Verified in v3.10.68: ORM auto-discovers database via `ensureDb()` which calls `Database::fromEnv()` reading `DATABASE_URL` from env. No explicit `$db` parameter needed: `$user = new User(); $user->where('active = 1');` works if DATABASE_URL is set in .env.
